# This file contains values from Cookiecutter

default_context:
  project_name: "todoist_quick_capture"
  project_description: "Awesome `todoist_quick_capture` is a Python cli/package created with https://github.com/Undertone0809/python-package-template"
  organization: "todoist_quick_capture"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "todoist_quick_capture"
  email: "public@richarddecal.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
